# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: cf03f9a644d8a0e931e752f2d3e99ddf28d779e302a6d6b0b3cde9a4a97b8e5c69c06fcad0316afc2809e3c5f55508bddb7a257e2ce8d6ce99517caa8513251a

test:
  secret_key_base: 1ebf1573e87717a98d859b95aefb821ec34a34e26dedb9e7a345321bac6232ea74022b9be6913266cf292ef5dcdee32983980e5f879377ff615473eceffe5569

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
